"""add defect category to inspections

Revision ID: 756fc6cd50c8
Revises: b33cf1824856
Create Date: 2026-09-12 22:20:25.168232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756fc6cd50c8'
down_revision: Union[str, Sequence[str], None] = 'b33cf1824856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('defect_category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'defect_category')
    # ### end Alembic commands ###
