"""add quality assessment fields to inspections

Revision ID: a96adcbc9a9e
Revises: e20f1b630737
Create Date: 2026-09-13 21:54:05.752088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a96adcbc9a9e'
down_revision: Union[str, Sequence[str], None] = 'e20f1b630737'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('quality_decision', sa.String(length=20), nullable=True))
    op.add_column('inspections', sa.Column('quality_assessment', sa.String(length=255), nullable=True))
    op.add_column('inspections', sa.Column('quality_recommendation', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'quality_recommendation')
    op.drop_column('inspections', 'quality_assessment')
    op.drop_column('inspections', 'quality_decision')
    # ### end Alembic commands ###
