"""add severity scoring fields to inspections

Revision ID: e20f1b630737
Revises: 756fc6cd50c8
Create Date: 2026-09-12 22:33:39.483119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e20f1b630737'
down_revision: Union[str, Sequence[str], None] = '756fc6cd50c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('severity_score', sa.Float(), nullable=True))
    op.add_column('inspections', sa.Column('severity_level', sa.String(length=20), nullable=True))
    op.add_column('inspections', sa.Column('quality_risk', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'quality_risk')
    op.drop_column('inspections', 'severity_level')
    op.drop_column('inspections', 'severity_score')
    # ### end Alembic commands ###
