"""add processing time fields to inspections

Revision ID: e94d6730c867
Revises: a96adcbc9a9e
Create Date: 2026-09-20 19:13:29.479202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e94d6730c867'
down_revision: Union[str, Sequence[str], None] = 'a96adcbc9a9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Both columns are nullable with no server default and no data backfill: every existing
    # inspection keeps NULL, because no timing was ever measured for it. NULL must never be
    # replaced with an estimated or zero value.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('processing_time_ms', sa.Float(), nullable=True))
    op.add_column('inspections', sa.Column('ai_inference_time_ms', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'ai_inference_time_ms')
    op.drop_column('inspections', 'processing_time_ms')
    # ### end Alembic commands ###
